version: "3"

services:
  rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-hydra
        environment:
            RABBITMQ_DEFAULT_USER: "hydra"
            RABBITMQ_DEFAULT_PASS: "hydra"
        ports:
          - "5672:5672"
          - "15672:15672"
  sql-server:
        image: alexandreyembo/hydra-sql-server:latest
        container_name: hydra-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "Prod@123"
            ACCEPT_EULA: "Y"

  identity-api:
        image:  alexandreyembo/hydra-identity-api:latest
        #  you might not use container_name if you are using load balance
        container_name: hydra-identity-api
        build: 
            context: ../../hydra-authentication
            dockerfile: ./dotnet3.1/Hydra.Identity.API/Dockerfile
        restart: always
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5101;http://+5102
            - ASPNETCORE_Kestrel__Certificates__Default__Password=hydra
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/hydra-certificate.pfx
        # volumes:
        # ro -> remote origin
            - ./certs:/https:ro
        depends_on:
          - rabbitmq
          - sql-server

#   basket-api:
#         image:  alexandreyembo/hydra-basket-api:latest
#         container_name: hydra-basket-api
#         build: 
#             context: ../../hydra-basket
#             dockerfile: ./dotnet3.1/Hydra.Basket.API/Dockerfile
#         restart: always
#         ports:
#   #     # the application wont run on this ports
#         - "5002:5002"          
#         environment: 
#             - ASPNETCORE_ENVIRONMENT=Production
#             - ASPNETCORE_URLS=https://+:55221;http://+55222
#         # volumes:
#         #     - ./certs:/https:ro
#         depends_on:
#           - rabbitmq
#           - redis
    # TODO LATER
#   hydra-server:
#         image:  alexandreyembo/hydra-server:latest
#         container_name: hydra-server
#         build: 
#             context: ./
#             dockerfile: ./nginx/Dockerfile
#         restart: always
#         ports:
#   #     # the application wont run on this ports
#         - "80:80"          
#         - "443:443"          
        
#         # volumes:
#         #     - ./certs:/https:ro
#         depends_on:
#           - hydra-ecommerce
       

 